from routes.route import Route

licenses_routes = [
    Route("licenses_index", "/",
          controller="cc.engine.licenses.views:licenses_view"),

    # publicdomain routing
    Route("license_deed_publicdomain", "/publicdomain/",
          controller="cc.engine.licenses.views:license_deed_view",
          code="publicdomain"),
    Route("license_rdf_publicdomain", "/publicdomain/rdf",
          controller="cc.engine.licenses.views:license_rdf_view",
          code="publicdomain"),
    Route("license_deed_explicit_publicdomain",
          "/publicdomain/deed", code="publicdomain",
          controller="cc.engine.licenses.views:license_deed_view"),
    Route("license_deed_lang_publicdomain",
          "/publicdomain/deed.{target_lang}", code="publicdomain",
          controller="cc.engine.licenses.views:license_deed_view"),

    Route("license_deed",
          "/{code}/{version}/",
          controller="cc.engine.licenses.views:license_deed_view"),
    Route("license_deed_explicit",
          "/{code}/{version}/deed",
          controller="cc.engine.licenses.views:license_deed_view"),
    Route("license_deed_lang",
          "/{code}/{version}/deed.{target_lang}",
          controller="cc.engine.licenses.views:license_deed_view"),
    Route("license_rdf",
          "/{code}/{version}/rdf",
          controller="cc.engine.licenses.views:license_rdf_view"),
    Route("license_legalcode",
          "/{code}/{version}/legalcode",
          controller="cc.engine.licenses.views:license_legalcode_view"),
    Route("license_legalcode_plain",
          "/{code}/{version}/legalcode-plain",
          controller="cc.engine.licenses.views:license_legalcode_plain_view"),
    Route("license_deed_jurisdiction",
          "/{code}/{version}/{jurisdiction}/",
          controller="cc.engine.licenses.views:license_deed_view"),
    Route("license_deed_jurisdiction_explicit",
          "/{code}/{version}/{jurisdiction}/deed",
          controller="cc.engine.licenses.views:license_deed_view"),
    Route("license_deed_lang_jurisdiction",
          "/{code}/{version}/{jurisdiction}/deed.{target_lang}",
          controller="cc.engine.licenses.views:license_deed_view"),
    Route("license_rdf_jurisdiction",
          "/{code}/{version}/{jurisdiction}/rdf",
          controller="cc.engine.licenses.views:license_rdf_view"),
    Route("license_legalcode_jurisdiction",
          "/{code}/{version}/{jurisdiction}/legalcode",
          controller="cc.engine.licenses.views:license_legalcode_view"),
    Route("license_legalcode_plain_jurisdiction",
          "/{code}/{version}/{jurisdiction}/legalcode-plain",
          controller="cc.engine.licenses.views:license_legalcode_plain_view"),

    # MIT / BSD routing
    Route("license_deed_mit", "/MIT/",
          controller="cc.engine.licenses.views:license_deed_view",
          code="MIT"),
    Route("license_deed_bsd", "/BSD/",
          controller="cc.engine.licenses.views:license_deed_view",
          code="BSD"),

    Route("license_legalcode_mit_redirect", "/MIT/legalcode",
          controller="cc.engine.licenses.views:license_legalcode_redirect",
          code="MIT"),
    Route("license_legalcode_bsd_redirect", "/BSD/legalcode",
          controller="cc.engine.licenses.views:license_legalcode_redirect",
          code="BSD"),
    Route("license_rdf_mit", "/MIT/rdf",
          controller="cc.engine.licenses.views:license_rdf_view",
          code="MIT"),
    Route("license_rdf_bsd", "/BSD/rdf",
          controller="cc.engine.licenses.views:license_rdf_view",
          code="BSD"),
]



cc0_routes = [
    Route("cc0_deed", "/{version}/",
          code='CC0', controller="cc.engine.licenses.views:license_deed_view"),
    Route("cc0_deed_explicit", "/{version}/deed",
          code='CC0', controller="cc.engine.licenses.views:license_deed_view"),
    Route("cc0_deed_lang", "/{version}/deed.{target_lang}",
          code='CC0', controller="cc.engine.licenses.views:license_deed_view"),
    Route("cc0_rdf", "/{version}/rdf",
          code='CC0', controller="cc.engine.licenses.views:license_rdf_view"),
    Route("cc0_legalcode", "/{version}/legalcode", code='CC0',
          controller="cc.engine.licenses.views:license_legalcode_view"),
    Route("cc0_legalcode_plain", "/{version}/legalcode-plain", code='CC0',
          controller="cc.engine.licenses.views:license_legalcode_plain_view")]
