<?php
$defaults=array(
  'title' => __('Archives', 'collapsArch'),
  'noTitle' => '',
  'inExcludeCat' => 'exclude',
  'inExcludeCats' => '',
  'inExcludeYear' => 'exclude',
  'inExcludeYears' => '',
  'showPages' => false, 
  'sort' => 'DESC',
  'linkToArch' => true,
  'showYearCount' => true,
  'expandCurrentYear' => true,
  'expandMonths' => true,
  'expandYears' => true,
  'expandCurrentMonth' => true,
  'showMonthCount' => true,
  'showPostTitle' => true,
  'expand' => '0',
  'showPostDate' => false,
  'debug' => '0',
  'postDateFormat' => 'm/d',
   'postDateAppend' => 'after',
  'animate' => 0,
  'postTitleLength' => '');
 ?>
