<master src="master">
<property name="title">Illegal Art | Creative Commons</property>

<h2>Features</h2>
<div class="smallcat">Featured artists, tools, and works</div>

<span class="feature-inside"><img src="/images/features/150illegalart.jpg" width="150" height="150" alt="Illegal Art" class="imgborder"  /></span> 

<h1>Take Another Little Piece of My Art</h1>
<p class="smalldates" style="font-size:10px;">Story by <a href="/about/people#23">Derek Slater</a><br />
July 2003</p>

<p>A museum exhibit called <a href="http://www.illegal-art.org/">"Illegal Art"</a> might sound like a history of naughty pictures. Turns out that the exhibit (through July 25 at <a href="http://www.sfmoma.org/museumstore/artists_overview.html">SF MOMA Artist's Gallery</a>) is more innocuous than most primetime TV: A Mickey Mouse gasmask. Pez candy dispensers honoring fallen hip-hop stars. A litigious Little Mermaid. Not kids' stuff, exactly&mdash;but <i>illegal</i>?</p>

<p>Copyright holders have threatened and sued many of the show's artists for sampling, remixing, and recontextualizing other people's artistic creations without permission. Featuring audio and visual exhibits, a full length CD, and several films, the show highlights how copyright, typically considered an engine of creativity, can stifle art and free speech.</p>

<p>"Copyright is often so esoteric and theoretical," said Carrie McLaren, the exhibit's curator. "We wanted to make copyright's problems as real to the average person as they are to our featured artists."</p>

<p>McLaren originally developed "Illegal Art" to support the <a href="http://www.eldred.cc/eldredvashcroft.html">unsuccessful legal challenge</a> to Congress' latest copyright extension. Copyrights <a href="http://www.arl.org/info/frn/copy/timeline.html">originally</a> lapsed after 14 years with a possible 14 year extension, allowing artists to build upon a rich array of past works. Disney, for example, recycled Snow White, Cinderella, and many other Brothers Grimm fairy tales that were public domain and thus free to reuse. Today, copyrights last 95 years for corporations or life plus 70 years for individual artists. Because of Congress' eleven retroactive term extensions over the last forty years, <a href="http://randomfoo.net/oscon/2002/lessig">no one can do to Disney what Disney did to the Brothers Grimm.</a></p>

<p>Until the terms end, copyright owners retain several <a href="http://www4.law.cornell.edu/uscode/17/ch1.html">exclusive rights</a>, including the right to make derivative works. Before you make Rocky X or remix Eminem's hit "Stan," you have to obtain permission&mdash;read: navigate a labyrinth of red tape&mdash;from the work's copyright holder. Every appropriation is presumptively a misappropriation.</p>

<p>Because this exclusive right is in tension with free speech, artists can invoke <a href="http://www4.law.cornell.edu/uscode/17/107.html">fair use</a> to defend their adaptations. Just as courts have protected controversial speech by <a href="http://www.bc.edu/bc_org/avp/cas/comm/free_speech/nytvsullivan.html">setting</a> high standards for <a href="http://chillingeffects.org/protest/faq.cgi#QID335">libel</a>, courts have identified commentary, criticism, and parody in particular as fair uses. </p>

<p>Most works in "Illegal Art" arguably fit this exception: they take "elements of our mass media environment to express how the artist feels about our culture," McLaren said. Some works probe the ways mass media mixes commerce and art, while other pieces twist societal icons to critique mainstream culture. Kieron Dwyer's <a href="http://www.illegal-art.org/print/index.html#consumer">"Consumer Whore"</a> graphic remakes the <a href="http://www.starbucks.com/images/homepage/home_cardtop_logostart.gif">Starbucks logo</A> into a preppy, cell-phone-yapping, princess of the dollar. </p>

<p>Nonetheless, the lack of a clear, consistent fair use doctrine has created a strong chilling effect on "Illegal Art" parodists and others like them. Judges use a complex balancing test that weighs the new work's purpose and commercial impact along with the degree to which the new work transforms the original, among other factors. Even when the Supreme Court <a href="http://supct.law.cornell.edu/supct/html/92-1292.ZS.html">ruled</a> that rap group 2 Live Crew was not liable for a parody of Roy Orbison's "Oh Pretty Woman," the Court indicated that parody's protection could be trumped in future cases.</p>

<p>Because of fair use's ambiguity, critical reuses are still regularly litigated. To avoid embarrassment, copyright holders may try to silence critics and parodists, who often do not have the financial resources to fight back. Though he convinced a judge that his work was a parody, Dwyer was <a href="http://www.toomuchcoffeeman.com/pages/mag_content/tm11/sued_pt2.html">unable</a> to 
fight on after a year in court and reluctantly agreed to a lopsided settlement. Who needs a <a href="http://chillingeffects.org/protest/faq.cgi#QID89">defamation</a> claim, likely to fall short of steep legal standards, when a simple <a href="http://chillingeffects.org/copyright/notice.cgi?NoticeID=285">copyright cease-and-desist letter</a> will do the trick?</p>

<p>The law is far less forgiving for uses that are not overtly parodic or critical, even if they are highly transformative or borrow only trivial portions. Rapper Biz Markie was <a href="http://www.ccnmtl.columbia.edu/projects/law/library/cases/case_grandwarner.html">told</a> by a judge "Thou shalt not steal" after he sampled twenty seconds of <a href="http://www.gilbertosullivan.com/music/lyrics/index.cfm?song=1318C5CE-1025-4072-AFC2-CCCB95499248">a Gilbert O'Sullivan track</a>. The ruling <a href="http://homepages.nyu.edu/~sv24/Chapter4.PDF">revolutionized rap</a> from <a href="http://www.publicenemy.com/lyrics/lyrics/caught-witness.php">share-and-share-alike</a> to <a href="http://www.p-diddy.com/pd/">pay-to-play</a>.</p>

<p>Sampling is now something that only people with significant wealth and the right contacts can do. When <a href="http://www.reddkross.com/fs.html">Redd Kross</a> rock guitarist Steve McDonald added bass tracks to his labelmates <a href="http://www.whitestripes.com/">The White Stripes'</a> "White Blood Cells," he was lucky enough to run into the band and <a href="http://mirrors.creativecommons.org/">get permission</a>. For most artists, clearing a copyright is too cumbersome, even when the sampled artists do not mind the sampling. Island Records sued Bay Area-based collage pioneers Negativland for parodying a U2 song, though, in a later interview, U2's lead guitarist <a href="http://www.negativland.com/edge.html">said</a> he "didn't have any problem with" the song and that "the lawsuit was not our lawsuit." </p>

<p>Had these legal limitations existed years ago, perhaps collage, rap, and Pop Art would have been sued to death before they ever had a chance to flourish. These days, the implication is that these appropriations are lower artforms, deserving legal treatment suited to petty thievery.</p>

<p>"The law presumes that sampling intends to undermine the work of others," said Mark Hosler of <a href="http://www.negativland.com">Negativland</a>, whose work is featured in the exhibit and who are helping to develop Creative Commons' <a href="http://creativecommons.org/discuss#sampling">sampling license</a>. "When we make our art to critique others, we're doing it because we're inspired by what we find, and I think that's true of many collage artists. Collage has been a legitimate form of art for a long time, and it's everywhere in today's society."</p>

<p>It's everywhere in part because <a href="http://www.fruity-loops.com/">cheap editing software</a> and the Internet have made sampling accessible to anyone. Thriving communities of <a href="http://groups.google.com/groups?hl=en&lr=&ie=UTF-8&group=alt.music.makers.dj">DJs</a>, <a href="http://www.detritus.net/">collagists</a>, and <a href="http://www.chillingeffects.org/fanfic/">"fan fiction"</a> writers collaborating on and sharing their works exist throughout the Web.</p>

<p>Sampling's everywhere for another reason. Corporate copyright holders, after years of battling the artform, are now appropriating it. Marketed as a near-revolution in filmmaking, Dreamworks has <a href="http://www.videoeta.com/news/1375">given</a> Mike Myers an exclusive right to insert himself into certain old movies. Meanwhile, several record labels are allowing people to combine three mainstream music tracks for a Lollapalooza concert <a href="http://www.cakewalk.com/Lollapalooza/">contest</a>; of course, all entrees immediately become <a href="http://www.cakewalk.com/Lollapalooza/Rules.asp">the labels' property</a>. Now that the "Illegal Art" artists and many more have popularized their artistic practice and suffered for it, corporate copyright holders are ready to reap the rewards. </p>

<p>To provoke a rethinking of how we treat appropriation art, the "Illegal Art" exhibit is touring the country to show people the value and plight of appropriation artists. Many groups are working alongside the exhibit to achieve its goals, like the <a href="http://www.chillingeffects.org">Chilling Effects Clearinghouse</a>, a joint effort by several law school clinics, that documents and assists accused online artists. </p>

<p><a href="http://www.creativecommons.org">Creative Commons</a> addresses the other end of copyright, providing artists with licenses that permit reuse of their works. Creative Commons licensing is in one sense a pragmatic solution to copyright's ills. Artists who want to license their works can easily express their preferences in a way that others can identify and trust. In this way, Creative Commons licensing has enabled collaborations that might otherwise require a lawyer and a dozen inquiries. For example, <a href="http://www.activefreemedia.org/people/">Colin Mutchler</a> submitted <a href="http://www.activefreemedia.com/gallery/music/colin/my_life.mp3">"My Life,"</a> an acoustic guitar song, to <a href="http://www.opsound.org">Opsound</a>, a music registry that requires <a href="http://creativecommons.org/licenses/by-sa/1.0/">Attribution-Share Alike</a> licensing; Cora Beth, <a href="http://www.creativecommons.org/weblog/entry/3744">a total stranger to Colin</a>, then layered a violin onto the song to make <a href="http://www.activefreemedia.com/gallery/music/colin/my_life_changed.mp3">"My Life Changed."</a> No copyright lawyers were consulted&mdash;or harmed&mdash;in the process.</p>

<p>In another sense, Creative Commons licensing is symbolic. It shows that alternatives to the current legal regime are possible. Artists can create a world where the law meets their expectations about legitimate appropriations &mdash; where museums and sterile McMash-Up contests aren't the only places to see new kinds of art.</p>

<p><a href="/images/">&laquo; Back to the Images section</a></p>