#
# Makefile to build some custom css rules
#

TODAY=`date +%F`

define DISCLAIMER =
endef

IE8_CSS =	css/normalize.css \
			css/bootstrap-1.2.0.css \
			css/skeleton.css \
			css/primary.styles.css \
			css/ie8-and-down-proto.css \
			css/media.queries-ie8-and-down.css \
			css/non-semantic.helper.classes.css \
			css/print.styles.css
    
IE8_OUTPUT= css/ie8-and-down.css

all: $(IE8_CSS)
	echo -e '/**' > $(IE8_OUTPUT)
	echo -e ' * THIS FILE IS AUTOGENERATED from Makefile. BE CAREFUL' \
		>> $(IE8_OUTPUT)
	echo " * $(TODAY)" >> $(IE8_OUTPUT)
	echo -e ' */' >> $(IE8_OUTPUT)
	cat $(IE8_CSS) >> $(IE8_OUTPUT)


# run if you using spaces , makefiles need tabs
# vim: set noexpandtab
