<!-- <li><a href="#">About CC</a></li> -->
<li><a href="/about/licenses/">The Licenses</a></li>
<li><a href="http://wiki.creativecommons.org/Newsletter">Newsletter</a></li>
<li><a href="/about/events">Events</a></li>
<li><a href="https://creativecommons.net/supporters">Supporters</a></li>
<li><a href="/about/opportunities">Jobs</a></li>
<li><a href="http://wiki.creativecommons.org/Developers">Developers</a></li>
<li><a href="http://wiki.creativecommons.org/Case_Studies">Case Studies</a></li>
<li><a href="/interviews">CC Talks With...</a></li>
<li><a href="http://creativecommons.org/education">Education</a></li>
<li><a href="http://sciencecommons.org/">Science</a></li>
<li><a href="/contact">Contact</a></li>
<!-- <li><a href="#">Documentation</a></li> -->
