<option value="http://creativecommons.org/international/ar/">Argentina</option>
<option value="http://creativecommons.org/international/au/">Australia</option>
<option value="http://creativecommons.org/international/at/">Austria</option>
<option value="http://creativecommons.org/international/be/">Belgium</option>
<option value="http://creativecommons.org/international/br/">Brazil</option>
<option value="http://creativecommons.org/international/bg/">Bulgaria</option>
<option value="http://creativecommons.org/international/ca/">Canada</option>
<option value="http://creativecommons.org/international/cl/">Chile</option>
<option value="http://creativecommons.org/international/cn/">China Mainland</option>
<option value="http://creativecommons.org/international/co/">Colombia</option>
<option value="http://creativecommons.org/international/hr/">Croatia</option>
<option value="http://creativecommons.org/international/dk/">Denmark</option>
<option value="http://creativecommons.org/international/ec/">Ecuador</option>
<option value="http://creativecommons.org/international/fi/">Finland</option>
<option value="http://creativecommons.org/international/fr/">France</option>
<option value="http://creativecommons.org/international/de/">Germany</option>
<option value="http://creativecommons.org/international/gr/">Greece</option>
<option value="http://creativecommons.org/international/gt/">Guatemala</option>
<option value="http://creativecommons.org/international/hk/">Hong Kong</option>
<option value="http://creativecommons.org/international/hu/">Hungary</option>
<option value="http://creativecommons.org/international/in/">India</option>
<option value="http://creativecommons.org/international/il/">Israel</option>
<option value="http://creativecommons.org/international/it/">Italy</option>
<option value="http://creativecommons.org/international/jp/">Japan</option>
<option value="http://creativecommons.org/international/kr/">Korea</option>
<option value="http://creativecommons.org/international/lu/">Luxembourg</option>
<option value="http://creativecommons.org/international/mk/">Macedonia</option>
<option value="http://creativecommons.org/international/my/">Malaysia</option>
<option value="http://creativecommons.org/international/mt/">Malta</option>
<option value="http://creativecommons.org/international/mx/">Mexico</option>
<option value="http://creativecommons.org/international/nl/">Netherlands</option>
<option value="http://creativecommons.org/international/nz/">New Zealand</option>
<option value="http://creativecommons.org/international/no/">Norway</option>
<option value="http://creativecommons.org/international/pe/">Peru</option>
<option value="http://creativecommons.org/international/ph/">Philippines</option>
<option value="http://creativecommons.org/international/pl/">Poland</option>
<option value="http://creativecommons.org/international/pt/">Portugal</option>
<option value="http://creativecommons.org/international/pr/">Puerto Rico</option>
<option value="http://creativecommons.org/international/ro/">Romania</option>
<option value="http://creativecommons.org/international/rs/">Serbia</option>
<option value="http://creativecommons.org/international/sg/">Singapore</option>
<option value="http://creativecommons.org/international/si/">Slovenia</option>
<option value="http://creativecommons.org/international/za/">South Africa</option>
<option value="http://creativecommons.org/international/es/">Spain</option>
<option value="http://creativecommons.org/international/se/">Sweden</option>
<option value="http://creativecommons.org/international/ch/">Switzerland</option>
<option value="http://creativecommons.org/international/tw/">Taiwan</option>
<option value="http://creativecommons.org/international/uk/">UK: England & Wales</option>
<option value="http://creativecommons.org/international/scotland/">UK: Scotland</option>
<option value="http://creativecommons.org/international/us/">United States</option>
